include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
     prefer_single_quotes: true
     avoid_web_libraries_in_flutter: false
     lines_longer_than_80_chars: false
     public_member_api_docs: false
     library_private_types_in_public_api: false
     implementation_imports: false